version: '3.8' # Docker Compose 버전 설정

services:
  spring-app:
    build:
      context: .                # 현재 디렉토리를 빌드 컨텍스트로 사용
      dockerfile: Dockerfile     # Dockerfile 지정 (기본값이므로 생략 가능)
    ports:
      - "8080:8080"             # 호스트 포트:컨테이너 포트 매핑
    environment:
      SPRING_PROFILES_ACTIVE: prod # Spring 프로파일 설정 예시 (필요에 따라 수정)
    networks:
      - app-network             # 네트워크 지정 (다른 서비스와 연결하려는 경우)

networks:
  app-network:
    driver: bridge              # 기본 네트워크 드라이버
