version: '3'  # Docker Compose 버전

services:
  zookeeper:
    image: bitnami/zookeeper:latest
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"

  kafka:
    image: bitnami/kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      ALLOW_PLAINTEXT_LISTENER: "yes"
    depends_on:
      - zookeeper  # Zookeeper가 먼저 시작되어야 Kafka가 실행됨
    networks:
      - app-network

  spring-app:
    build:
      context: .  # Dockerfile이 있는 현재 디렉토리
    ports:
      - "8081:8080"  # 호스트:컨테이너 포트 매핑
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      HOST: ${HOST}
      S3_BUCKET : ${S3_BUCKET}
      S3_ACCESSKEY : ${S3_ACCESSKEY}
      S3_SECRETKEY : ${S3_SECRETKEY}
    depends_on:
      - kafka  # Kafka가 먼저 시작된 후 Spring 앱 시작
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
