spring:
  data:
    mongodb:
      uri: mongodb://${DB_USERNAME}:${DB_PASSWORD}@${HOST}:27017/mootd?authSource=admin

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB


#카프카 설정 컨피그 파일로 대체
  kafka:
    bootstrap-servers: "kafka:9092"  # Kafka 서버 주소
#    consumer:
#      auto-offset-reset: "earliest"       # 메시지를 처음부터 읽도록 설정
#      key-deserializer: "org.apache.kafka.common.serialization.StringDeserializer"
#      value-deserializer: "org.apache.kafka.common.serialization.JsonDeserializer"
#      properties.spring.kafka.consumer.trusted.packages: "com.bwd4.mootd.dto.internal"  # 패키지 신뢰 설정
#    producer:
#      key-serializer: "org.apache.kafka.common.serialization.StringSerializer"
#      value-serializer: "org.apache.kafka.common.serialization.JsonSerializer"


cloud:
  aws:
    s3:
      bucket: ${S3_BUCKET}
    stack.auto: false
    region.static: ap-northeast-2
    credentials:
      accessKey: ${S3_ACCESSKEY}
      secretKey: ${S3_SECRETKEY}

springdoc:
  swagger-ui:
    path: swagger

ai:
  host: ${HOST}


management:
  endpoints:
    web:
      exposure:
        include: prometheus, health, info
  metrics:
    tags:
      application: ${spring.application.name}