version: "3.8"

services:
  app:
    build:
      context: .  # Dockerfile이 있는 디렉토리
    container_name: image-similarity
    ports:
      - "8001:80"  # 로컬 포트 8001을 컨테이너의 80 포트로 매핑
    command: ["uvicorn", "mainapp:app", "--host", "0.0.0.0", "--port", "80"]
